### ISSUE TITLE
Is there anyway to not wait for the task to finish

### ISSUE THREAD

**Issue by atomicwrite** [geekcell/github-action-aws-ecs-run-task#21]
I have some really long running ones. Yours is the only plugin that works. I turned logs off -- will that just exec the task and go?

**Comment by Ic3w0lf** [comment]
Hey @atomicwrite 

there has been a PR open for this exact feature for a while, but I didn't yet have the time to implement and test it properly #20. Maybe I will find some time for it this week.

Right now the pipeline will wait for the task to finish before exiting.

Best regards

**Comment by Ic3w0lf** [comment]
Added an option to disable waiting for tasks in #24
