### ISSUE TITLE
I'm using v4.1.0, but still warning upgrade AWS CDK V3

### ISSUE THREAD

**Issue by longnenosta** [geekcell/github-action-aws-ecs-run-task#31]
<img width="1022" alt="Screenshot 2024-11-01 at 14 26 58" src="https://github.com/user-attachments/assets/2301e141-dcfb-4edc-8bd4-2702fd0adf3d">

I see that from version 4.1.0, you’ve upgraded AWS CDK to V3, but I still see this warning.

**Comment by Ic3w0lf** [comment]
@longnenosta Thanks opening an issue! I know there is still some old SDK code left in the repo, as it still uses a deprecated node dependency which uses the SDKv2. I was working on replacing this in my PR, but sadly AWS changed quiet some stuff in v3, so I have to rewrite some bigger parts which I didn't have time for yet 😢 

I am planning on continue working on this hopefully this week. Cheers!

**Comment by Ic3w0lf** [comment]
@longnenosta I finally found some time to replace the SDKv2 (this time completely, hopefully). I released a v5 in #30. Feel free to test it and let me know if it works for you!
